Allow all Keystatic patch updates
Thinkmill/keystatic-starter-landing-page pull request #3
Opened 2023-05-26 00:43 UTC by ChrisLaneAU

Some installations of the starter template are throwing on navigation to `/keystatic`. Updating the `@keystatic` packages to the latest versions fixes the issue. This PR just moves us to `x` patch versions of `@keystatic` package allowing the latest patches to be installed while Keystatic is in pre-release.

From the [node semver docs on caret ranges](https://github.com/npm/node-semver#caret-ranges-123-025-004):
> ^0.0.3 := >=0.0.3 <0.0.4-0
> ^0.0.x := >=0.0.0 <0.1.0-0

2023-05-26 01:26 UTC, emmatown requested changes
This is not safe, we'll be making breaking changes frequently while in `0.0.x`

2023-05-26 01:34 UTC, ChrisLaneAU commented
> This is not safe, we'll be making breaking changes frequently while in `0.0.x`

Cool cool, thanks for this sanity check! I'm thinking we'll have to keep an eye on versions manually for the time being. I'll just update to the latest. Thanks again!

2023-05-26 01:47 UTC, emmatown reviewed
The carets should still be kept even though they're essentially doing nothing here, they're helpful to communicate that they're not intentionally pinned to a specific version (they're just essentially implicitly pinned because we're in `0.0.x`).

2023-05-28 23:50 UTC, jtbrolin approved these changes

2023-05-28 23:51 UTC, jtbrolin approved these changes

2023-05-28 23:56 UTC, emmatown approved these changes

2023-06-01 00:37 UTC, merged